### ISSUE TITLE
Bugs Checking

### ISSUE THREAD

**Issue by Josphat205** [MoRaad97/First-Capstone-Project#3]
- The project looks good congrats.
- Your partner section looks good but it could be better if you can increase the margin to give a better spacing between elements.
- You have a nice logo great, it could be better if you can give a link to the home page.

**Comment by MoRaad97** [comment]
> * The project looks good congrats.
> * Your partner section looks good but it could be better if you can increase the margin to give a better spacing between elements.
> * You have a nice logo great, it could be better if you can give a link to the home page.

Thanks. all The issues are fixed.
